notifications:
  email: false

language: python

jobs:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      dist: xenial
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - pip3 install -U pip
    - name: "Python 3.7 on Xenial Linux"
      os: linux
      dist: xenial          # required for Python >= 3.7
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - pip3 install -U pip
    - name: "Python 3.8 on Xenial Linux"
      os: linux
      dist: xenial          # required for Python >= 3.7
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - pip3 install -U pip
    - name: "Python 3.9 on Xenial Linux"
      os: linux
      dist: xenial          # required for Python >= 3.7
      python: 3.9-dev       # this works for Linux but is ignored on macOS or Windows
      before_install:
        - pip3 install -U pip
    - name: "Python 3.6 on MacOS"
      os: osx
      osx_image: xcode9.4     # Python 3.6 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
    - name: "Python 3.7 on MacOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7 running on macOS 10.14
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
    - name: "Python 3.8 on MacOS"
      os: osx
      osx_image: xcode12.2  # Python 3.7 running on macOS 10.15
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.1
        - python -m pip install --upgrade pip
        - chcp.com 65001
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - PYTHONIOENCODING=UTF-8
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
        - chcp.com 65001
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - PYTHONIOENCODING=UTF-8
    - name: "Python 3.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - chcp.com 65001
      env: 
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - PYTHONIOENCODING=UTF-8
    - name: "Python 3.9 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.9.0
        - python -m pip install --upgrade pip
        - chcp.com 65001
      env:
        - PATH=/c/Python39:/c/Python39/Scripts:$PATH
        - PYTHONIOENCODING=UTF-8

install:
  - pip3 install codecov
  - pip3 install -r requirements.txt

script:
 - coverage run test.py

after_success:
 - codecov
